name: TeleportSystem
version: '${project.version}'
main: de.kevrecraft.teleportsystem.TeleportSystem
api-version: '1.20'

commands:
  home:
    description: Ein einfacher /home Befehl!
  warp:
    description: Ein einfacher /warp Befehl!
  spawn:
    description: Ein einfacher /spawn Befehl!